
service: register-patient
plugins:
  - serverless-offline
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1

functions:
  showPatients:
    handler: handler.showPatients
    events: 
      - http:
          path: patients
          method: get

  showPatient:
    handler: handler.showPatient
    events: 
      - http:
          path: patients/{patientId}
          method: get
