service: register-patient
plugins:
  - serverless-offline
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1

iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:PutItem
      - dynamodb:DeleteItem
      - dynamodb:GetItem
    Resource: arn:aws:dynamodb:us-east-1:306891557711:table/PATIENTS

functions:
  showPatients:
    handler: handler.showPatients
    events:
      - http:
          path: patients
          method: get

  showPatient:
    handler: handler.showPatient
    events:
      - http:
          path: patients/{patientId}
          method: get

resources:
  Resources:
    PatientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PATIENTS
        AttributeDefinitions:
          - AttributeName: patient_id
            AttributeType: S
        KeySchema:
          - AttributeName: patient_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
